#!/usr/bin/env bash

# Golang
export GOROOT=/home/stephan/applications/go1.10
export PATH=$PATH:$GOROOT/bin
export GOPATH=/home/stephan/source/gopath
export PATH=$PATH:$GOPATH/bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:/home/stephan/applications/tmux/bin
function ts {
    args=$@
    tmux send-keys -t right "$args" C-m
}

~/dotfiles/bin/tell-me-a-joke
~/dotfiles/bin/weather
