#!/usr/bin/env bash

# Golang
export GOROOT=/home/stephan/applications/go1.10
export PATH=$PATH:$GOROOT/bin
export GOPATH=/home/stephan/source/gopath
export PATH=$PATH:$GOPATH/bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:/home/stephan/applications/tmux/bin
function ts {
    args=$@
    tmux send-keys -t right "$args" C-m
}
CTERM="\e[0m"
GREEN="\e[32m"
RED="\e[31m"
BLUE="\e[34m"

_c() {
   echo -e $1
}

_clr() {
   echo -e "${CTERM}"
}
#GREEN="$(tput setaf 2)"
#RED="$(tput setaf 1)"
#BLUE="$(tput setaf 4)"
#CTERM="$(tput sgr0)"
#CYAN="$(tput setaf 6)"
function _git_changes() {
   local CHANGES=$(git diff-index HEAD | wc -l)
   [[ "${CHANGES}" != "0" ]] && echo ": ${CHANGES} changes" 
}

function _git_branch() {
   if [[ -d ".git" ]]; then
	   echo " $(_c ${RED})[`git rev-parse --abbrev-ref HEAD`$(_git_changes)]$(_clr)"
   fi
}

PS1='$(_c ${GREEN})[\A]${_clr} $(_c ${CYAN})\u$(_clr):\w$(_git_branch) \$ '
~/dotfiles/bin/tell-me-a-joke
~/dotfiles/bin/weather



