#!/usr/bin/env bash

# Golang
export GOROOT=/home/stephan/applications/go1.10
export PATH=$PATH:$GOROOT/bin
export GOPATH=/home/stephan/source/gopath
export PATH=$PATH:$GOPATH/bin

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:/home/stephan/applications/tmux/bin
function ts {
    args=$@
    tmux send-keys -t right "$args" C-m
}
#CTERM="\e[0m"
#GREEN="\e[32m"
#RED="\e[31m"
#BLUE="\e[34m"

GREEN="$(tput setaf 2)"
RED="$(tput setaf 1)"
BLUE="$(tput setaf 4)"
CTERM="$(tput sgr0)"
CYAN="$(tput setaf 6)"
function _git_branch() {
   if [[ -d ".git" ]]; then
      echo "${RED}[`git rev-parse --abbrev-ref HEAD`]${CTERM}"
   fi
}
PS1='${GREEN}[\A]${CTERM} ${CYAN}\u${CTERM}@\h:\w$(_git_branch) \$ '
~/dotfiles/bin/tell-me-a-joke
~/dotfiles/bin/weather


